apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS db_exemple;
    USE db_exemple;
    CREATE TABLE IF NOT EXISTS MESSAGE (
      id INT PRIMARY KEY,
      name VARCHAR(255),
      message VARCHAR(255)
    );