apiVersion: v1
kind: Service
metadata:
  name: heart
spec:
  ports:
    - nodePort: 31280
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: heart
  type: NodePort
  